// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test800x480

#include "../ui.h"


// IMAGE DATA: assets/LOGO_loading_70.png
lv_img_dsc_t ui_img_logo_loading_70_png = {
    .header.always_zero = 0,
    .header.w = 1024,
    .header.h = 600,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_logo_loading_70_png_load()
{
    ui_img_logo_loading_70_png.data = UI_LOAD_IMAGE("S:assets/ui_img_logo_loading_70_png.bin", 1843200);
    ui_img_logo_loading_70_png.data_size = 1843200;
}
