// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test800x480

#ifndef _TEST800X480_UI_H
#define _TEST800X480_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "ui_img_manager.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_img_dsc_t ui_img_logo_loading_70_png;   // assets/LOGO_loading_70.png
void ui_img_logo_loading_70_png_load();
extern lv_img_dsc_t ui_img_config_led_std_png;   // assets/Config_LED_Std.png
void ui_img_config_led_std_png_load();

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
